/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_calculator;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void  test1plus1(){
    Representation rep = new Representation(1.0,1.0,'+');
    double calc = Calculator.calculate(rep);
    assertEquals(2.0,calc, 0.0);
  }
  @Test
  public void  test7multiply8(){
    Representation rep = new Representation(7.0,8.0,'*');
    double calc = Calculator.calculate(rep);
    assertEquals(56.0,calc, 0.0);
  }
}
